### ISSUE TITLE
[Discussion] about state machine with love 😄

### ISSUE THREAD

**Issue by beeth0ven** [pierremrtn/state_machine_bloc#1]
Hi there,

Thank for your great work to develop this library!
I'm pretty happy to see this state management solution, and feel it a bit similar to one I'm currently using:
https://pub.dev/packages/love
I'm interesting in state management area, so I'd  like to discuss about different soluttions. 
What do you thing about state machine with [love](https://pub.dev/packages/love) 😄?

**Comment by pierremrtn** [comment]
Thank you for sharing 👍 !

Honestly, I didn't know about `love` package before. I've taken a little tour. It looks like it has been designed with redux in mind, which I never used either, so my opinion will be very superficial, correct me if I'm wrong.

Looking at the interface, it looks very similar to what bloc does. `System<Event, State>` stands for `Bloc<Event, State>`. Therefore it looks like it has the same "problem" that I'm trying to address bloc that I'm trying to address with this package. The system does not restrict you to a set of states. Instead, you update the inner state with `dispatch` (or `reduce` ? not sure), that's what bloc does with `emit`. That doesn't mean you can't restrict yourself to a finite state of states. Just the API isn't designed in that way.

`state_machine_bloc` isn't a new state management solution. Its aim is to add another tool to bloc state management package that you can use when it feels right, for example when the correctness of state is critical.

That said, state machine concept is not limited to a specific state management solution. I think it's totally feasible create state machine for the `love` package too.  For that reason I was thinking about separating the state machine from the integration with bloc, that way It would be usable with any state management solution.

**Comment by beeth0ven** [comment]
Thank you for your reply!

I'm not familar with finite state machine, your statement helped me a lot to learn it.

> Instead, you update the inner state with dispatch (or reduce ? not sure), that's what bloc does with emit.

Yeah, In [love](https://pub.dev/packages/love) or redux `dispatch` is equivalent  to `bloc.add`, it add a event to the system.

> That said, state machine concept is not limited to a specific state management solution. I think it's totally feasible create state machine for the love package too. For that reason I was thinking about separating the state machine from the integration with bloc, that way It would be usable with any state management solution.

That's would be great. If you decide to create a shared state machine. I'm glad to be a tester.

It seems finite state machine enforce us to declare state using union like type as:
https://bloclibrary.dev/#/fluttertimertutorial?id=timerstate

Intuition tells me that in some pratical situations, use finite state model is not that easy (I may be wrong  😄). Would like to see your opinion.

For example, if we have a list page, the data is fetched async from backend.
After the data is successfully fetched, user pull the list to trigger a refresh. 
while refreshing we need  to show old list items.
this ux is common, we can find it in pinterest mobile app:
https://apps.apple.com/us/app/pinterest/id429047995

## 1
if we model state as:

```dart
class AsyncPosts {
  AsyncPosts({
    required this.loading,
    required this.error,
    required this.posts,
  })
  final bool loading;
  final Object? error;
  final List<Post>? posts;

  ... // copyWith, toString etc.
}
```

We can express the state pretty easy:

```dart
// idle
AsyncPosts(
  loading: false,
  error: null,
  posts: null
);

// loading
AsyncPosts(
  loading: true,
  error: null,
  posts: null
);

// success
AsyncPosts(
  loading: false,
  error: null,
  posts: [...]
);

//  error
AsyncPosts(
  loading: false,
  error: Exception(...),
  posts: null
);

// loading with previous posts
AsyncPosts(
  loading: true,
  error: null,
  posts: [...] // <- keep previous posts
);

// error with previous posts
AsyncPosts(
  loading: false,
  error: Exception(...), 
  posts: [...] // <- keep previous posts
);
```

With the UI it's pretty straightforward to bind each preperties to each UI element:

```dart
Widget build(BuildContext context, AsyncPosts asyncPost) {
   return ListView(
    children: [
      if (asyncPost.loading) _buildSpinner(),
     ...(asyncPost.posts ?? []).map((post) => ListTile(...)),
    ],
  )
}
```

## 2 
If we model state as finite like :

```dart
abstract class AsyncPosts {}

class Idle implements AsyncPosts {
}

class Loading implements AsyncPosts {
  Loading(this.posts);
  final List<Post>? posts;
}

class Success implements AsyncPost {
  Loading(this.posts);
  final List<Post>? posts;
}

class Error implements AsyncPosts {
  Error(this.error, this.posts);
  final Object error;
  final List<Post>? posts;
}
```

In the UI layer we need handle each case like this:

```dart
Widget build(BuildContext context, AsyncPosts asyncPost) {
  final bool loading;
  fianl List<Post>? posts;
  if (asyncPosts is Idle) {
    loading = false;
    posts = null;
  } else if (asyncPosts is Loading) {
    loading = true;
    post = asyncPosts.posts
  } else if ...
     ...
  }
   return ListView(
    children: [
      if (loading) _buildSpinner(),
     ...(posts ?? []).map((post) => ListTile(...)),
    ],
  )
}
```

I feel in this situation, the first state model seems a bit straightforward. I currently haven't come up with a good way to handle this with finite state model.

What do you think about this problem?

**Comment by pierremrtn** [comment]
Thank you for your great comment and example, it helps push the discussion forward!

> Intuition tells me that in some practical situations, using a finite state model is not that easy (I may be wrong 😄). Would like to see your opinion.

That's true. State machine is less flexible than bloc and Cubit. It's the cost you pay to benefit from its robustness.

First, let looks at your example:
```dart
class AsyncPosts {
  AsyncPosts({
    required this.loading,
    required this.error,
    required this.posts,
  })
  final bool loading;
  final Object? error;
  final List<Post>? posts;

  ... // copyWith, toString etc.
}
```
It's a really interesting example cause even if it's a small one it already suffering from problems described in articles linked inside the resources section of the readme. 
The main problem is that you have to manage state's flags by hand in your bloc, like so:

```dart
AsyncPostBloc() : super(AsyncPostState(
    loading: true,
    error: null,
    posts: [],
)) {
    _requestPost();
    on<PostReceived>(_onPostReceived);
    on<Refresh>(_onRefresh);
}

_onPostReceived(event, emit) {
    emit(AsyncPostState(
            loading: false,
            error: event.error,
            posts: event.post,
    ))
}

_onRefresh(event, emit) {
    emit(AsyncPostState.copyWith(
            loading: true,
            error: null,
            post: []
    ))
    _requestPost();
}
```
As you can see, most of the code here is managing the state's flags. If you forget to set loading to false after receiving data, your list will load indefinitely.
Again it's a simple case. Imagine if you had 2 more flags to handle.
You will also have to protect onRefresh to be executed while requesting posts.

If you forget a check or set an incorrect flag value somewhere it immediately introduces a bug in your logic. That is exactly what I'm trying to fix with state_machine_bloc. 

Now we have analyzed implementation without a state machine, let's see what we can do with it.

```dart
abstract class AsyncPostsState {}

class Loading implements AsyncPostsState {}

class Success implements AsyncPostsState {
  Success(this.posts);
  final List<Post>? posts;
}

class Error implements AsyncPostsState {
  Error(this.error);
  final Object error;
}

AsyncPostStateMachine() : super(Loading()) {
    define<Loading>((b) => b
        ..onEnter(_requestPosts)
        ..on<PostReceived>(_onPostReceived)
    ):
    define<Success>((b) => b
        ..on<Refresh>(_onRefresh)
    );
    define<Error>((b) => b
        ..on<Refresh>(_onRefresh)
    );
}

AsyncPostsState _onPostReceived(PostReceived event, Loading state) {
    if (event.isError) return Error(event.error);
    else return Success(event.success);
}

Loading _onRefresh(Refresh event, AsyncPostState state) {
    return Loading();
}
```

Voilà! As you can see, logic it's much easier to understand and maintain.
Something interesting here is the refresh function
```dart
Loading _onRefresh(Refresh event, AsyncPostState state) {
    return Loading();
}
```
As you can see, I'm using AsyncPostState to specify that it can be used inside any state.
We can do that because the prototype of the state builder function (what you pass to on<Event> func) is 
```dart
FutureOr<State?> Function(DefinedEvent extends Event, DefinedState extends State)
```
Thanks to the flexibility of dart compiler you can be very expressive about what transition do. Every following syntax can be used as on<Event> parameter
```dart
//on event, compute a and transit to b
StateB _onX(Event, StateA)

//on event, compute a and maybe transit to b
StateB? _onX(Event, StateA)

//on event, compute current state of any type and maybe transit to any state
State? _onX(Event, State)

//on event, compute an asynchronously and maybeTransit to b
Future<StateB>? _onX(Event, StateA)
```
In addition, we don't have to prevent on refresh to be called while we are in Loading state, it's just impossible cause we didn't specify onRefresh transition for this state.

Lastly, in the future nested state will let us define on<Refresh> transition for both Success and Error at once, and maybe there will be support for transitions based on receiving a future for cases similar to Loading state.

**Comment by pierremrtn** [comment]
Reading this again I realized that I didn't answer you on the UI part.

Instead of 
```dart
Widget build(BuildContext context, AsyncPosts asyncPost) {
  final bool loading;
  fianl List<Post>? posts;
  if (asyncPosts is Idle) {
    loading = false;
    posts = null;
  } else if (asyncPosts is Loading) {
    loading = true;
    post = asyncPosts.posts
  } else if ...
     ...
  }
   return ListView(
    children: [
      if (loading) _buildSpinner(),
     ...(posts ?? []).map((post) => ListTile(...)),
    ],
  )
}
```

just do

```dart
Widget build(BuildContext context, AsyncPosts asyncPost) {
  //find state using provider package
   final state = context.select((MyStateMachine sm) => sm.state);
   if (state is Loading) return SpinnerWidget()
   if (state is Error) return ErrorWidget();
   if (state is Success) { //state is implicitly casted to Success
     return ListView(
      children: [
        state.posts.map((post) => ListTile(...)).toList(),
      ],
    )
  }
}
```
Voilà!

Also, good news, I've worked on state_machine_bloc today, I came up with a new implementation and I think I will be able to successfully decouple the state machine from its bloc integration.
I think it will be ready to try in 1 or 2 weeks.

**Comment by beeth0ven** [comment]
Thanks for your patience!

I feel your light, it's strong and warm!  Helped me a lot to gain knownlege about finite state machine.

> As you can see, most of the code here is managing the state's flags. If you forget to set loading to false after receiving data, your list will load indefinitely.
Again it's a simple case. Imagine if you had 2 more flags to handle.
You will also have to protect onRefresh to be executed while requesting posts.

> If you forget a check or set an incorrect flag value somewhere it immediately introduces a bug in your logic. That is exactly what I'm trying to fix with state_machine_bloc.

That's a good point! With finite state machine, I can see the code is more rigorous and less error prone.

> Voilà! As you can see, logic it's much easier to understand and maintain.
Something interesting here is the refresh function

Yes, the logic is easier to understand as it enforce us to write logic in a declarative way 👍 .

```dart
FutureOr<State?> Function(DefinedEvent extends Event, DefinedState extends State)
```
> Thanks to the flexibility of dart compiler you can be very expressive about what transition do. Every following syntax can be used as on parameter

That's pretty smart, I haven't used it before. Get a new skill today, thank you again!

> Reading this again I realized that I didn't answer you on the UI part.

```dart
Widget build(BuildContext context, AsyncPosts asyncPost) {
  //find state using provider package
   final state = context.select((MyStateMachine sm) => sm.state);
   if (state is Loading) return SpinnerWidget()
   if (state is Error) return ErrorWidget();
   if (state is Success) { //state is implicitly casted to Success
     return ListView(
      children: [
        state.posts.map((post) => ListTile(...)).toList(),
      ],
    )
  }
}
```

That would work. It scope state in a more natural way. I'd prefer to use finite state mathine when solving problem.

> Also, good news, I've worked on state_machine_bloc today, I came up with a new implementation and I think I will be able to successfully decouple the state machine from its bloc integration.
I think it will be ready to try in 1 or 2 weeks.

That's pretty interesting, please take your time. thanks for your amazing work 👍!

**Comment by pierremrtn** [comment]
While working on the separation of state machine from its bloc implementation I've realized that I was doing the same things bloc already do so I have abandoned this idea.

The good news is since StateMachine is a Bloc, it's can already be used outside flutter :) So if you want to use this state machine with your own state management solution, just import `state_machine_bloc` and then you can do:
```dart
final sm = MyStateMachine();
sm.add(Event);
sm.stream // access state's stream
sm.state //access current state
await sm.close() // don't forget to close it !
```
It will eventually work on a standalone package but I think this solution is ok so it will not be one of my priorities.

Also, version 0.0.1-dev.2 is out, with nested states support and better side effect api!

**Comment by beeth0ven** [comment]
> While working on the separation of state machine from its bloc implementation I've realized that I was doing the same things bloc already do so I have abandoned this idea.

that's fine, implementing some repetitive logic, probably not a good idea. it's good to coupled with bloc, since bloc is amazing too 👍.

>The good news is since StateMachine is a Bloc, it's can already be used outside flutter :) So if you want to use this state machine with your own state management solution, just import state_machine_bloc and then you can do

I get the idea how state machine works, i will try to experiment it. What I'm a little concerned is about the practical use case. For example the [Flutter Infinite List Tutorial](https://bloclibrary.dev/#/flutterinfinitelisttutorial?id=flutter-infinite-list-tutorial), if we rewrite the example using state machine, is the state machine solution better than current one. I'm not 100% sure about this. I'm thinking about it 😄.

**Comment by pierremrtn** [comment]
I'll spend some time next week experimenting with state machines and implementing more examples since I have done all features I wanted for the first version.
There are probably cases where it's better to use bloc instead of sm. It's important to find these cases to understand better what this package should do, as pointed out in the bloc's proposal.
Thank you to pointing out the infinite list case, I will work on it and I will let you know what I'll found :).

**Comment by beeth0ven** [comment]
Yeah, If we have a guide about when to use state machine and when to use bloc, that will make a lot of sense.
Thanks for you great works.

**Comment by pierremrtn** [comment]
I've just uploaded infinite list state machine version on branch 0.0.1-dev.3 !
I think sm version is better, but I would love to hear what you think about it.
I'm working on writing guides for example and when to use state machine but its taking time, I'll let you know when I'll make progress on this.

**Comment by beeth0ven** [comment]
>I've just uploaded infinite list state machine version on branch 0.0.1-dev.3 !
I think sm version is better, but I would love to hear what you think about it.
I'm working on writing guides for example and when to use state machine but its taking time, I'll let you know when I'll make progress on this.

Please take your time. Thank you for adding this example 👍 

Yeah, I can see the finite state machine solution is cleaner.

I will list original approach(bloc) vs finite state machine approach to increase muscle memory:

## Event:

### bloc:

```dart
abstract class PostEvent extends Equatable {
  @override
  List<Object> get props => [];
}

class PostFetched extends PostEvent {}
```

### finite state machine:

```dart
abstract class PostEvent extends Equatable {
  const PostEvent();
  @override
  List<Object> get props => [];
}

class PostFetchRequested extends PostEvent {}

class PostFetchSuccess extends PostEvent {
  const PostFetchSuccess({
    required this.posts,
  });

  final List<Post> posts;

  @override
  List<Object> get props => [posts];
}

class PostFetchError extends PostEvent {
  const PostFetchError({
    required this.error,
  });

  final String error;

  @override
  List<Object> get props => [error];
}
```

## State

### bloc:

```dart

enum PostStatus { initial, success, failure }

class PostState extends Equatable {
  const PostState({
    this.status = PostStatus.initial,
    this.posts = const <Post>[],
    this.hasReachedMax = false,
  });

  final PostStatus status;
  final List<Post> posts;
  final bool hasReachedMax;

  PostState copyWith({
    PostStatus? status,
    List<Post>? posts,
    bool? hasReachedMax,
  }) {
    return PostState(
      status: status ?? this.status,
      posts: posts ?? this.posts,
      hasReachedMax: hasReachedMax ?? this.hasReachedMax,
    );
  }

  @override
  String toString() {
    return '''PostState { status: $status, hasReachedMax: $hasReachedMax, posts: ${posts.length} }''';
  }

  @override
  List<Object> get props => [status, posts, hasReachedMax];
}
```

### finite state machine:

```dart

abstract class PostState extends Equatable {
  const PostState({required this.posts});

  final List<Post> posts;

  @override
  List<Object> get props => [posts];
}

class PostInitial extends PostState {
  const PostInitial() : super(posts: const []);
}

class PostSuccess extends PostState {
  const PostSuccess({required List<Post> posts}) : super(posts: posts);
}

class PostError extends PostState {
  const PostError({required List<Post> posts, required this.error})
      : super(posts: posts);

  final String error;

  @override
  List<Object> get props => [posts, error];
}

class PostFetchInProgress extends PostState {
  const PostFetchInProgress({required List<Post> posts}) : super(posts: posts);
}

class PostEndReached extends PostState {
  const PostEndReached({required List<Post> posts}) : super(posts: posts);
}
```

## BLOC/FSM

### bloc:

```dart

const _postLimit = 20;
const throttleDuration = Duration(milliseconds: 100);

EventTransformer<E> throttleDroppable<E>(Duration duration) {
  return (events, mapper) {
    return droppable<E>().call(events.throttle(duration), mapper);
  };
}

class PostBloc extends Bloc<PostEvent, PostState> {
  PostBloc({required this.httpClient}) : super(const PostState()) {
    on<PostFetched>(
      _onPostFetched,
      transformer: throttleDroppable(throttleDuration),
    );
  }

  final http.Client httpClient;

  Future<void> _onPostFetched(
    PostFetched event,
    Emitter<PostState> emit,
  ) async {
    if (state.hasReachedMax) return;
    try {
      if (state.status == PostStatus.initial) {
        final posts = await _fetchPosts();
        return emit(state.copyWith(
          status: PostStatus.success,
          posts: posts,
          hasReachedMax: false,
        ));
      }
      final posts = await _fetchPosts(state.posts.length);
      posts.isEmpty
          ? emit(state.copyWith(hasReachedMax: true))
          : emit(
              state.copyWith(
                status: PostStatus.success,
                posts: List.of(state.posts)..addAll(posts),
                hasReachedMax: false,
              ),
            );
    } catch (_) {
      emit(state.copyWith(status: PostStatus.failure));
    }
  }

  Future<List<Post>> _fetchPosts([int startIndex = 0]) async {
    final response = await httpClient.get(
      Uri.https(
        'jsonplaceholder.typicode.com',
        '/posts',
        <String, String>{'_start': '$startIndex', '_limit': '$_postLimit'},
      ),
    );
    if (response.statusCode == 200) {
      final body = json.decode(response.body) as List;
      return body.map((dynamic json) {
        return Post(
          id: json['id'] as int,
          title: json['title'] as String,
          body: json['body'] as String,
        );
      }).toList();
    }
    throw Exception('error fetching posts');
  }
}
```

### finite state machine:

```dart

const _postLimit = 20;
const throttleDuration = Duration(milliseconds: 100);

// EventTransformer<E> throttleDroppable<E>(Duration duration) {
//   return (events, mapper) {
//     return droppable<E>().call(events.throttle(duration), mapper);
//   };
// }

class PostBloc extends StateMachine<PostEvent, PostState> {
  PostBloc({required this.httpClient}) : super(const PostInitial()) {
    define<PostInitial>((b) => b
      ..on<PostFetchRequested>(
        _transitToFetchInProgress,
      ));

    define<PostSuccess>((b) => b
      ..on<PostFetchRequested>(
        _transitToFetchInProgress,
      ));

    define<PostFetchInProgress>(
      (b) => b
        ..onEnter(_fetchPosts)
        ..on<PostFetchSuccess>(_onPostFetchSuccess)
        ..on<PostFetchError>(_onPostFetchError),
    );

    define<PostError>();

    define<PostEndReached>();
  }

  final http.Client httpClient;

  PostFetchInProgress _transitToFetchInProgress(
    PostFetchRequested event,
    PostState state,
  ) =>
      PostFetchInProgress(posts: state.posts);

  PostState _onPostFetchSuccess(
    PostFetchSuccess event,
    PostFetchInProgress state,
  ) {
    if (event.posts.isNotEmpty) {
      return PostSuccess(posts: List.of(state.posts)..addAll(event.posts));
    } else {
      return PostEndReached(posts: state.posts);
    }
  }

  PostError _onPostFetchError(
    PostFetchError event,
    PostFetchInProgress state,
  ) =>
      PostError(
        posts: state.posts,
        error: event.error,
      );

  Future<void> _fetchPosts(PostFetchInProgress state) async {
    final startIndex = state.posts.length;
    try {
      final response = await httpClient.get(
        Uri.https(
          'jsonplaceholder.typicode.com',
          '/posts',
          <String, String>{'_start': '$startIndex', '_limit': '$_postLimit'},
        ),
      );
      if (response.statusCode == 200) {
        final body = json.decode(response.body) as List;
        final posts = body
            .map((dynamic json) => Post(
                  id: json['id'] as int,
                  title: json['title'] as String,
                  body: json['body'] as String,
                ))
            .toList();
        add(PostFetchSuccess(posts: posts));
      }
      add(PostFetchError(error: response.statusCode.toString()));
    } catch (e) {
      add(PostFetchError(error: e.toString()));
    }
  }
}
```

## My Opinion

The original bloc solution is simple and flexible, the finite state machine solution is strict and much more clean  👍. Also I see the event transformer comment:

```dart
// EventTransformer<E> throttleDroppable<E>(Duration duration) {
//   return (events, mapper) {
//     return droppable<E>().call(events.throttle(duration), mapper);
//   };
// }
```

I know bloc had a powerful event ticket system by using stream operators ([bloc_concurrency](https://pub.dev/packages/bloc_concurrency)).

There are mainly 4 strategies:

1. concurrent - process events concurrently
2. sequential - process events sequentially
3. droppable - ignore any events added while an event is processing
4. restartable - process only the latest event and cancel previous event handlers

I think if finite state machine could support this feature, that would be amazing. I feel it's very challenging 😄

A simple test(use) case is "search bar":
1. drop high frequency input (quick typing), debounce input keyword
2. after the keyword is confirmed, cancel previous pending search if exist, then trigger current search

Can refer to [this article](https://verygood.ventures/blog/how-to-use-bloc-with-streams-and-concurrency)'s **Checking username availability** section.

**Comment by pierremrtn** [comment]
With StateMachine's current design, if you use it for a search bar with two states, Typing and RequestingApi, high-frequency inputs will not be processed while in state RequestingApi. To "drop" requests if new inputs are received, you should add an event handler for RequestingAPI state cancel API request. I admit that it's not ideal but still ok.

I think it's feasible to implement event transformers, but it's out of scope for v0.0.1, eventually for v0.0.2, because I plan to publish a v0.0.1 as soon as possible.

That said thinking about it I'm not sure it makes sense to have event transformers for StateMachine or even the use case you've described fit well with StateMachine. My first assumption for sm was that transitions should be evaluated sequentially and no other event will be processed before all transitions finished evaluation.
I think having custom event transformers go against this idea. It is a good idea to let transitions be evaluated concurrently for example?

For me, it's more like a first clue about when to use Bloc in favor of StateMachines.
Do you have a set of well-defined states? Use state machine.
Do you have only one big state or do you need complex event transformations? Use Bloc.

It's just my thought however, this should be discussed.

**Comment by beeth0ven** [comment]
Thanks for your patience.

>With StateMachine's current design, if you use it for a search bar with two states, Typing and RequestingApi, high-frequency inputs will not be processed while in state RequestingApi. To "drop" requests if new inputs are received, you should add an event handler for RequestingAPI state cancel API request. I admit that it's not ideal but still ok.

Yeah, Add `RequestCancel` event handler will solve the problem. em.. If that's the case, I guess StateMachine is not easy to model state that will change parameters over time, for exmaple loading progress state:

```dart
class LoadingProgress extends SomeState {
  const LoadingProgress(this.progress);
  final double progress;
  ...
}
```

Since the state is distinct by it's type (Class Here) without comparing it's parameters. This may be a clue about when to use bloc, when to use StateMachines.

>That said thinking about it I'm not sure it makes sense to have event transformers for StateMachine or even the use case you've described fit well with StateMachine. My first assumption for sm was that transitions should be evaluated sequentially and no other event will be processed before all transitions finished evaluation.
I think having custom event transformers go against this idea. It is a good idea to let transitions be evaluated concurrently for example?

>For me, it's more like a first clue about when to use Bloc in favor of StateMachines.
Do you have a set of well-defined states? Use state machine.
Do you have only one big state or do you need complex event transformations? Use Bloc.

>It's just my thought however, this should be discussed.

Thanks for the explaination, I get it, the StateMachine are mainly for well-defined states and events are handled in sequentially.

>I think it's feasible to implement event transformers, but it's out of scope for v0.0.1, eventually for v0.0.2, because I plan to publish a v0.0.1 as soon as possible.

Got it, I'm okay with current design, please follow your plan, thank you very much 👍!

**Comment by pierremrtn** [comment]
> Thanks for your patience.

I'm happy to answer your question ! It's nice to see your interest in this project :) Asking me question challenge me and helping me better understand this project so thank you for this.

About the loader example:
```dart
class LoadingProgress extends SomeState {
  const LoadingProgress(this.progress);
  final double progress;
  ...
}
```
It should be fine, you just need to implement == operator like any state used with bloc. You could do it with equatable or freezed. Then you will be able to do something like this:
```dart
define<Loading>(($) => $
    ..on<Increment>((event, state) => Loading(state.progress + event.progress))
);
```
It's will work cause state machine (or bloc) will use == operator to compare current state with next state.

To push things further, with state machine in its current design, the first time you will enter Loading state, Loading's **onEnter** side effect will be triggered. Then, each time you will transit from Loading to another Loading state (with different progress), **onChange** will be triggered, but not **onEnter**.

```dart
define<Loading>(($) => $
    ..onEnter( /** start loader**/ )
    ..onChange(/** log or what else **/)
);
```

**Comment by beeth0ven** [comment]
>I'm happy to answer your question ! It's nice to see your interest in this project :) Asking me question challenge me and helping me better understand this project so thank you for this.

That's my pleasure. I'm pretty interest in state management area and I'm happy to discuss with you about state machine.

> It should be fine, you just need to implement == operator like any state used with bloc. You could do it with equatable or freezed. Then you will be able to do something like this:

>To push things further, with state machine in its current design, the first time you will enter Loading state, Loading's onEnter side effect will be triggered. Then, each time you will transit from Loading to another Loading state (with different progress), onChange will be triggered, but not onEnter.

Yes, I can see the `onChange` callback is what I need when state changes while it's in same status. Thanks for the explaination. It helps me a lot to understand state machine 👍

**Comment by pierremrtn** [comment]
v0.0.1 is out 🎉

I'm closing this issue to launch with a repo without issues.
Thank you for your interest in this project, feel free to open new issues or contribute :)

I hope you will like this package 💙
