### ISSUE TITLE
Redefining state definition API

### ISSUE THREAD

**Issue by pierremrtn** [pierremrtn/state_machine_bloc#2]
## Redefining StateMachine's state definition builder API.

StateMachine definition API is being reworked and will change in the next release.

### state's transition:
State transition remains unchanged. They are registered by calling stateDefinitionBuilder's on<Event> function.
They are in the form:
```dart
FutureOr<State?> Function(Event, DefinedState)
```
Transitions are evaluated sequentially. They are always awaited.
If transition returns a non-null state, the state machine stops evaluating transitions and changes its inner state. If transition return null, transition is considered refused and the next transition is evaluated.

### state's side effects:
Side effects are callback functions that you can register for each state. They are a good place for calling repository functions. 
Side effects are in the form:
```dart
void function(State currentState)
```
They can be async but they will not be awaited.
If you need to update/change state machine state based inside side effect, you should add an event to the StateMachine with `add` function.

You have access to 3 side effects slot:

**onEnter**: called when entering state if currentState.runtimeType != nextState.runtimeType

**onChange**: called when state data updated, if currentState.runtimeType == nextState.runtimeType

**onExit**: called when exiting state, if currentState.runtimeType == nextState.runtimeType

### Example

```dart
class Example extends StateMachine<Event, State> {
  Example() : super(Counter(0)) {
    define<Counter>((b) => b
      ..onEnter((Counter state) { /*
      called on entering. In this case when the StateMachine will be constructed
      */ }),
      ..on<ButtonPressed>((ButtonPressed event, Initial state) =>
          state.value < 10 ? Counter(state.value + 1) : Done()
      ),
      ..onChanged((Counter state) => print(state.value)),
      ..onExit((Initial state) { /* state.value equal 10 */ }),
    );
    define<Done>((b) => b
      ..onEnter((Done state) { /* called on entering */ }),
      ..onChange((Done state) { /* Never called in this case ! */ }),
    );
}
```

What do you think about the new api? Do you have any suggestions? Give your feedback in the comments below :)

**Comment by EnesKaraosman** [comment]
I would expect `on(EventTransition)` to be a Future, I might do single/multiple API call, so `onEnter` does not solve my problem here, do you have any recommendation for handling `Future`s @Pierre2tm

**Comment by pierremrtn** [comment]
Nice to see you've tried state_machine_bloc!

With the actual design, you should create an event corresponding to the result of your API call. Events should be thrown inside a side effect function.

Example:
```dart
import 'package:state_machine_bloc/state_machine_bloc.dart';

part 'user_repository.dart';
part 'login_event.dart';
part 'login_state.dart';

class LoginStateMachine extends StateMachine<LoginEvent, LoginState> {
  LoginStateMachine({
    required this.userRepository,
  }) : super(WaitingFormSubmission()) {
    define<WaitingFormSubmission>(
        ($) => $..on<LoginFormSubmitted>(_toTryLoggingIn));

    define<TryLoggingIn>(($) => $
      ..onEnter(_login)
      ..on<LoginSucceeded>(_toSuccess)
      ..on<LoginFailed>(_toError));

    define<LoginSuccess>();
    define<LoginError>();
  }

  final UserRepository user repository;

  TryLoggingIn _toTryLoggingIn(LoginFormSubmitted event, state) =>
      TryLoggingIn(email: event.email, password: event.password);

  LoginSuccess _toSuccess(e, s) => LoginSuccess();

  LoginError _toError(LoginFailed event, state) => LoginError(event.reason);

  /// Use state's data to try login-in using the API
  Future<void> _login(TryLoggingIn state) async {
    try {
      await userRepository.login(
        email: state.email,
        password: state.password,
      );
      add(LoginSucceeded());
    } catch (e) {
      add(LoginFailed(e.toString()));
    }
  }
}
``` 

Sync transition has the benefits of greatly simplifying the underlying implementation and avoiding events concurrency and weird situations because of await in transitions.

I also think this limitation forces us to have a clean state machine code with great separation of concerns.

Since this issue is already closed and implemented in the current published version, if you want to dig further into this subject please open a new issue.
